
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kandi
 */
public class edit_user extends javax.swing.JFrame {

    /**
     * Creates new form edit_user
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public edit_user() {
        initComponents();
        
        txtusername.setText(dashboard.userid);
        
    conn = MySqlConnect.ConnectDB();

    try{
    String sql="select * from registration where username='"+ dashboard.userid +"'";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();    
    while(rs.next()){
    String first_name =rs.getString("firstname");
    txtFirstname.setText(first_name);
    String last_name =rs.getString("lastname");
    txtLastname.setText(last_name);
    String phone =rs.getString("mobile");
    txtphone.setText(phone);
    String email =rs.getString("email");
    txtemail.setText(email);
    }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerbutton4 = new javax.swing.JButton();
        txtoldpass = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        registerbutton1 = new javax.swing.JButton();
        registerbutton5 = new javax.swing.JButton();

        registerbutton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton4.setText("Exit");
        registerbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtoldpass.setBackground(new java.awt.Color(0, 0, 0));

        username.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");

        firstname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setText("First name:");

        lastname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setText("Last name:");

        registerbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton.setText("Edit");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone number:");

        email.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email id:");

        txtusername.setEditable(false);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        txtFirstname.setEditable(false);

        txtLastname.setEditable(false);

        txtphone.setEditable(false);
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        txtemail.setEditable(false);

        registerbutton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton1.setText("Save");
        registerbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton1ActionPerformed(evt);
            }
        });

        registerbutton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton5.setText("Exit");
        registerbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtoldpassLayout = new javax.swing.GroupLayout(txtoldpass);
        txtoldpass.setLayout(txtoldpassLayout);
        txtoldpassLayout.setHorizontalGroup(
            txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtoldpassLayout.createSequentialGroup()
                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtoldpassLayout.createSequentialGroup()
                        .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtoldpassLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(txtoldpassLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username)
                                    .addComponent(firstname)
                                    .addComponent(lastname)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtoldpassLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(phone)
                                .addGap(1, 1, 1)))
                        .addGap(68, 68, 68)
                        .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(txtFirstname)
                            .addComponent(txtLastname)
                            .addComponent(txtphone)
                            .addComponent(txtemail)))
                    .addGroup(txtoldpassLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(registerbutton)
                        .addGap(83, 83, 83)
                        .addComponent(registerbutton1)
                        .addGap(56, 56, 56)
                        .addComponent(registerbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        txtoldpassLayout.setVerticalGroup(
            txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtoldpassLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addGap(18, 18, 18)
                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname))
                .addGap(18, 18, 18)
                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(txtoldpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbutton)
                    .addComponent(registerbutton1)
                    .addComponent(registerbutton5))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtoldpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // TODO add your handling code here:
       txtFirstname.setEditable(true);
       txtLastname.setEditable(true);
       txtphone.setEditable(true);
       txtemail.setEditable(true);
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void registerbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            
            String value1=txtFirstname.getText();
            String value2=txtLastname.getText();
            String value3=txtphone.getText();
            String value4=txtemail.getText();
            
            String sql="update registration set firstname='"+value1+"', lastname='"+value2+"', mobile='"+value3+"', email='"+value4+"' where username='"+ dashboard.userid +"' ";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated successfully");
            txtFirstname.setEditable(false);
            txtLastname.setEditable(false);
            txtphone.setEditable(false);
            txtemail.setEditable(false);
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_registerbutton1ActionPerformed

    private void registerbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbutton4ActionPerformed

    private void registerbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton5ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_registerbutton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel phone;
    private javax.swing.JButton registerbutton;
    private javax.swing.JButton registerbutton1;
    private javax.swing.JButton registerbutton4;
    private javax.swing.JButton registerbutton5;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPanel txtoldpass;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
