
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kandi
 */
public class edit_password extends javax.swing.JFrame {

    /**
     * Creates new form edit_password
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public edit_password() {
        initComponents();
        txtusername.setText(dashboard.userid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtoldpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtnewpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtconfpass = new javax.swing.JPasswordField();
        registerbutton3 = new javax.swing.JButton();
        showpassword1 = new javax.swing.JCheckBox();
        showpassword2 = new javax.swing.JCheckBox();
        showpassword3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        registerbutton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Old Password:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password:");

        registerbutton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton3.setText("Save Password");
        registerbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton3ActionPerformed(evt);
            }
        });

        showpassword1.setBackground(new java.awt.Color(46, 49, 49));
        showpassword1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        showpassword1.setForeground(new java.awt.Color(255, 255, 255));
        showpassword1.setText("Show Password");
        showpassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword1ActionPerformed(evt);
            }
        });

        showpassword2.setBackground(new java.awt.Color(46, 49, 49));
        showpassword2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        showpassword2.setForeground(new java.awt.Color(255, 255, 255));
        showpassword2.setText("Show Password");
        showpassword2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword2ActionPerformed(evt);
            }
        });

        showpassword3.setBackground(new java.awt.Color(46, 49, 49));
        showpassword3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        showpassword3.setForeground(new java.awt.Color(255, 255, 255));
        showpassword3.setText("Show Password");
        showpassword3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpassword3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");

        txtusername.setEditable(false);

        registerbutton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton5.setText("Exit");
        registerbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(registerbutton3)
                        .addGap(58, 58, 58)
                        .addComponent(registerbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addGap(33, 33, 33)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtoldpass, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(txtnewpass)
                        .addComponent(txtconfpass))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(showpassword3)
                        .addComponent(showpassword2)
                        .addComponent(showpassword1))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbutton3)
                    .addComponent(registerbutton5))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(showpassword1)
                                .addComponent(jLabel1)
                                .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(showpassword2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtconfpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showpassword3))
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton3ActionPerformed
        // TODO add your handling code here:
        String user, pass;
        conn = MySqlConnect.ConnectDB();
        String Sql = "select * from registration where username=?";
        try {
            pst = conn.prepareStatement(Sql);
            pst.setString(1, dashboard.userid);
            rs = pst.executeQuery();
            if (rs.next()) {
                user = rs.getString("username");
                pass = rs.getString("password");
                if (pass.equals(txtoldpass.getText()) && txtnewpass.getText().equals(txtconfpass.getText())) {

                    String Sql1 = "update registration set password=? where username=?";
                    try {
                        pst = conn.prepareStatement(Sql1);
                        pst.setString(1, txtnewpass.getText());
                        pst.setString(2, txtusername.getText());
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Password Successfully changed");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Password");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Password ");
                txtoldpass.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_registerbutton3ActionPerformed

    private void showpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword1ActionPerformed
        // TODO add your handling code here:
        if (showpassword1.isSelected()) {
            txtoldpass.setEchoChar((char) 0);
        } else {
            txtoldpass.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassword1ActionPerformed

    private void showpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword2ActionPerformed
        // TODO add your handling code here:
        if (showpassword2.isSelected()) {
            txtnewpass.setEchoChar((char) 0);
        } else {
            txtnewpass.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassword2ActionPerformed

    private void showpassword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword3ActionPerformed
        // TODO add your handling code here:
        if (showpassword3.isSelected()) {
            txtconfpass.setEchoChar((char) 0);
        } else {
            txtconfpass.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassword3ActionPerformed

    private void registerbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton5ActionPerformed
//        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_registerbutton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerbutton3;
    private javax.swing.JButton registerbutton5;
    private javax.swing.JCheckBox showpassword1;
    private javax.swing.JCheckBox showpassword2;
    private javax.swing.JCheckBox showpassword3;
    private javax.swing.JPasswordField txtconfpass;
    private javax.swing.JPasswordField txtnewpass;
    private javax.swing.JPasswordField txtoldpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
