
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kandi
 */
import java.sql.*;
import java.text.DateFormat;
import javax.swing.*;
import java.util.Date;
import java.text.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

public class product_expiry extends javax.swing.JFrame {

    /**
     * Creates new form product_expiry
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
String outD,todaydate;
    public product_expiry() {
        initComponents();
        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Date date = new Date();
        txtdate.setDate(date);

        showData("", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        months = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        exp_date = new com.toedter.calendar.JDateChooser();
        txtdate = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Expiry");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(46, 49, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Months:");

        months.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "1 month", "2 months", "3 months", "4 months", "5 months", "6 months" }));
        months.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthsActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKU", "Product Name", "Stock", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtdate.setDateFormatString("dd-MM-yyyy");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Today Date");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Expiry Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(exp_date, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addComponent(months, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jLabel4))
                            .addComponent(exp_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*void showtabledata()
      {
       
        try{
            conn=MySqlConnect.ConnectDB();
        String Sql="select sku as 'SKU', product_name as 'Product Name', stock as 'Stock', expiry as 'Expiry date' from inventory_page where expiry >='"+outD+"'";// between '"+txtdate.getDate().toString()+"' and '"+outD+"'";
            pst=conn.prepareStatement(Sql);
          //  pst.setString(1, txtdate.getDate().toString());
            //pst.setString(2, outD);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
      }*/
void showtabledata()
      {
       
        try{
            conn=MySqlConnect.ConnectDB();
        String Sql="select * from inventory_page where expiry BETWEEN ? AND ?";
            pst=conn.prepareStatement(Sql);
             pst.setString(1, todaydate);
                pst.setString(2, outD);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
      }

    public void showData(String d1, String d2) {

        try {
            conn = MySqlConnect.ConnectDB();
            // if no date selected display all data
            if (d1.equals("") && d2.equals("")) {
                String Sql = "SELECT sku as 'SKU', product_name as 'Product Name', stock as 'Stock', expiry as 'Expiry date' FROM inventory_page";
                pst = conn.prepareStatement(Sql);
            } else {
                String sql = "SELECT sku as 'SKU', product_name as 'Product Name', stock as 'Stock', expiry as 'Expiry date' FROM inventory_page WHERE expiry BETWEEN ? AND ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, d1);
                pst.setString(2, d2);
            }
                rs = pst.executeQuery();
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                Object[] row;

                while (rs.next()) {
                    row = new Object[4];
                    row[0] = rs.getString(1);
                    row[1] = rs.getString(2);
                    row[2] = rs.getString(3);
                    row[3] = rs.getString(4);

                    model.addRow(row);
                }
        } catch (Exception e) {

            System.out.println(e.getMessage());

        }
    }
    private void monthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthsActionPerformed
        // TODO add your handling code here:
//String ADate=df.format(txtdate.getDate());
        /*try {
            DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            
            if (months.getSelectedIndex() == 1) {
                jTable1.setModel(new DefaultTableModel(null, new Object[]{"sku", "product_name", "stock", "expiry"}));
                Date date = txtdate.getDate();
                Calendar cal = Calendar.getInstance();
                cal.add(Calendar.DAY_OF_MONTH, 30);
                Date futureDate = cal.getTime();
                 outD = df.format(futureDate);
                 todaydate = df.format(date);
                JOptionPane.showMessageDialog(null, " JTable Updated SUCCESSFULL " + outD);
               // showData(todaydate,outD);
               showtabledata();
                
            } else if (months.getSelectedIndex() == 2) {
                jTable1.setModel(new DefaultTableModel(null, new Object[]{"sku", "product_name", "stock", "expiry"}));
                Date date = txtdate.getDate();
                Calendar cal = Calendar.getInstance();
                cal.add(Calendar.DAY_OF_MONTH, 60);
                Date futureDate = cal.getTime();
                 outD = df.format(futureDate);
                 todaydate = df.format(date);
                JOptionPane.showMessageDialog(null, " JTable Udated SUCCESSFULL " + outD);
               // showData(todaydate,outD);
               showtabledata();
                
            } else if (months.getSelectedIndex() == 3) {
                jTable1.setModel(new DefaultTableModel(null, new Object[]{"sku", "product_name", "stock", "expiry"}));
                Date date = txtdate.getDate();
                Calendar cal = Calendar.getInstance();
                cal.add(Calendar.DAY_OF_MONTH, 90);
                Date futureDate = cal.getTime();
                 outD = df.format(futureDate);
                 todaydate = df.format(date);
                JOptionPane.showMessageDialog(null, " JTable Udated SUCCESSFULL " + outD);
               // showData(todaydate,outD);
               showtabledata();
                
            } else if (months.getSelectedIndex() == 4) {
                jTable1.setModel(new DefaultTableModel(null, new Object[]{"sku", "product_name", "stock", "expiry"}));
                Date date = txtdate.getDate();
                Calendar cal = Calendar.getInstance();
                cal.add(Calendar.DAY_OF_MONTH, 120);
                Date futureDate = cal.getTime();
                 outD = df.format(futureDate);
                 todaydate = df.format(date);
                JOptionPane.showMessageDialog(null, " JTable Udated SUCCESSFULL " + outD);
               // showData(todaydate,outD);
               showtabledata();
                
            } else if (months.getSelectedIndex() == 5) {
                jTable1.setModel(new DefaultTableModel(null, new Object[]{"sku", "product_name", "stock", "expiry"}));
                Date date = txtdate.getDate();
                Calendar cal = Calendar.getInstance();
                cal.add(Calendar.DAY_OF_MONTH, 150);
                Date futureDate = cal.getTime();
                 outD = df.format(futureDate);
                 todaydate = df.format(date);
                JOptionPane.showMessageDialog(null, " JTable Udated SUCCESSFULL " + outD);
               // showData(todaydate,outD);
               showtabledata();
                
            } else if (months.getSelectedIndex() == 6) {
                jTable1.setModel(new DefaultTableModel(null, new Object[]{"sku", "product_name", "stock", "expiry"}));
                Date date = txtdate.getDate();
                Calendar cal = Calendar.getInstance();
                cal.add(Calendar.DAY_OF_MONTH, 180);
                Date futureDate = cal.getTime();
                 outD = df.format(futureDate);
                 todaydate = df.format(date);
                JOptionPane.showMessageDialog(null, " JTable Udated SUCCESSFULL " + outD);
                //showData(todaydate,outD);
                showtabledata();
            }
        } catch (Exception e) {

        }*/
    }//GEN-LAST:event_monthsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            
            jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id","Full Name","Address","BirthDate"}));
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = df.format(txtdate.getDate());
            String date2 = df.format(exp_date.getDate());
            
            showData(date1, date2);
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_expiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_expiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_expiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_expiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_expiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser exp_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> months;
    private com.toedter.calendar.JDateChooser txtdate;
    // End of variables declaration//GEN-END:variables
}
