/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kandi
 */
import java.sql.*;
import javax.swing.*;
import java.sql.SQLException;
public class registrationpage extends javax.swing.JFrame {

    /**
     * Creates new form registrationpage
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement stmt;
public static String username1;
    public registrationpage() {
        initComponents();
        //center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        createanaccount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        reenterpass = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();
        registerbutton = new javax.swing.JButton();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        showpassword2 = new javax.swing.JCheckBox();
        showpassword1 = new javax.swing.JCheckBox();
        loginaccount = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtrepassword = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        createanaccount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        createanaccount.setForeground(new java.awt.Color(255, 255, 255));
        createanaccount.setText("No account? Click here to register");
        createanaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createanaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createanaccountMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REGISTRATION FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        username.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");

        password.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");

        reenterpass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        reenterpass.setForeground(new java.awt.Color(255, 255, 255));
        reenterpass.setText("Re-enter Password:");

        firstname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setText("First name:");

        lastname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setText("Last name:");

        resetbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        registerbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerbutton.setText("Register");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone number:");

        email.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email id:");

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        showpassword2.setBackground(new java.awt.Color(46, 49, 49));
        showpassword2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        showpassword2.setForeground(new java.awt.Color(255, 255, 255));
        showpassword2.setText("Show Password");
        showpassword2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword2ActionPerformed(evt);
            }
        });

        showpassword1.setBackground(new java.awt.Color(46, 49, 49));
        showpassword1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        showpassword1.setForeground(new java.awt.Color(255, 255, 255));
        showpassword1.setText("Show Password");
        showpassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword1ActionPerformed(evt);
            }
        });

        loginaccount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginaccount.setForeground(new java.awt.Color(255, 255, 255));
        loginaccount.setText("Already have an account? Click here to login");
        loginaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginaccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(username)
                                        .addComponent(lastname)
                                        .addComponent(password))
                                    .addComponent(firstname)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phone)
                                    .addComponent(reenterpass)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpassword)
                            .addComponent(txtrepassword, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtLastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showpassword2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showpassword1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginaccount)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(registerbutton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstname)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(showpassword1)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reenterpass)
                    .addComponent(showpassword2)
                    .addComponent(txtrepassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbutton)
                    .addComponent(registerbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(loginaccount)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // TODO add your handling code here:
      
        try{
           if (txtusername.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Please enter username");
               return;
        }
           if (txtpassword.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Please enter password");
               return;
        }
           if (txtrepassword.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Please enter password");
               return;
        }
           if (txtFirstname.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Please enter first name");
               return;
        }
           if (txtLastname.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Please enter last name");
               return;
        }
           if (txtphone.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Please enter phone no.");
               return;
        }
        if (txtemail.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Please enter email id");
               return;
        }
        if (!(txtpassword.getText()).equals(txtrepassword.getText())){
               JOptionPane.showMessageDialog(this, "Password doesn't match");
               return;
        }
        if (txtpassword.getText().length()<5){
            JOptionPane.showMessageDialog(this, "Password must have atleast 5 characters");
               return;
        }
        }
        catch(Exception e){
        }
        
        /*String sql1="Select username from registration where username = '"+txtusername.getText()+"'";
        try{
        stmt = conn.createStatement();
        rs=stmt.executeQuery(sql1);
        if(rs.next()){
            JOptionPane.showMessageDialog(this, "Username already exists");
            txtusername.setText("");
            return;
        }
        }catch(Exception e){
        }*/
        
        conn = MySqlConnect.ConnectDB();
        String Sql = "INSERT INTO registration VALUES(?,?,?,?,?,?) ";
        try {

            pst = conn.prepareStatement(Sql);
            pst = conn.prepareStatement(Sql);
            pst.setString(1, txtusername.getText());
           username1 = txtusername.getText();
            pst.setString(2, txtpassword.getText());
            pst.setString(3, txtFirstname.getText());
            pst.setString(4, txtLastname.getText());
            pst.setString(5, txtphone.getText());
            pst.setString(6, txtemail.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "SUCCESSFULLY REGISTERED");
                this.hide();
                
                dashboard hp = new dashboard();
                hp.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Username already exists" );
        }
        

        
        conn = MySqlConnect.ConnectDB();
        String sql2 = "INSERT INTO login_form VALUES(?,?) ";
        try {

            pst = conn.prepareStatement(sql2);
            pst = conn.prepareStatement(sql2);
            pst.setString(1, txtusername.getText());
            pst.setString(2, txtpassword.getText());
            pst.executeUpdate();
            reset();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void reset(){
    txtusername.setText(null);
    txtpassword.setText(null);
    txtrepassword.setText(null);
    txtFirstname.setText(null);
    txtLastname.setText(null);
    txtphone.setText(null);
    txtemail.setText(null);
    }

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void showpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword2ActionPerformed
        // TODO add your handling code here:
        if (showpassword2.isSelected()) {
            txtrepassword.setEchoChar((char)0);
        } else {
            txtrepassword.setEchoChar('*');
        }

    }//GEN-LAST:event_showpassword2ActionPerformed

    private void showpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword1ActionPerformed
        // TODO add your handling code here:
        if (showpassword1.isSelected()) {
            txtpassword.setEchoChar((char)0);
        } else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassword1ActionPerformed

    private void createanaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createanaccountMouseClicked

    }//GEN-LAST:event_createanaccountMouseClicked

    private void loginaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginaccountMouseClicked
        // TODO add your handling code here:
        login_form supf = new login_form();
        supf.setVisible(true);
        supf.pack();
        supf.setLocationRelativeTo(null);
        this.hide();

    }//GEN-LAST:event_loginaccountMouseClicked

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createanaccount;
    private javax.swing.JLabel email;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel loginaccount;
    private javax.swing.JLabel password;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel reenterpass;
    private javax.swing.JButton registerbutton;
    private javax.swing.JButton resetbutton;
    private javax.swing.JCheckBox showpassword1;
    private javax.swing.JCheckBox showpassword2;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphone;
    private javax.swing.JPasswordField txtrepassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
